import type { Metadata } from 'next';
import { Noto_Sans_KR, Sigmar } from 'next/font/google';

import './globals.css';
import BackBtn from '@/_components/common/BackBtn';

const sigmar = Sigmar({
  weight: '400',
  variable: '--font-sigmar',
  subsets: ['latin'],
});

const notoSansKor = Noto_Sans_KR({
  weight: '400',
  variable: '--font-noto-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${notoSansKor.variable} ${sigmar.variable} antialiased`}
        style={{
          fontFamily:
            'var(--font-sigmar), var(--font-noto-sans), Arial, Helvetica, sans-serif',
        }}
      >
        <BackBtn />
        {children}
      </body>
    </html>
  );
}
