import type { Metadata } from 'next';
import { Sigmar } from 'next/font/google';
import './globals.css';

const sigmar = Sigmar({
  weight: '400',
  variable: '--font-sigmar',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sigmar.variable} antialiased`}
        style={{
          fontFamily: 'var(--font-sigmar), Arial, Helvetica, sans-serif',
        }}
      >
        {children}
      </body>
    </html>
  );
}
